### PR TITLE
fix: get correct version from package.json

### PR DESCRIPTION
**Pull request by aj-may**

### CODE REVIEW

**Review by codfish — COMMENTED** [review]
semantic won't auto update that file, I think you need to update git plugin settings, no?

**Comment by aj-may** [comment]
@codfish I think this actually is fine.

**Comment by codfish** [comment]
> @codfish I think this actually is fine.

why? you're building before running semantic no?

**Review by codfish — APPROVED** [review]
This will work for npm installs, but not pkg installs. 👍 for now, but you need to change how you run your builds.  https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package-jsons-version

**Review by codfish — APPROVED** [review]

**Pull request merged**
